/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sample API
 * サンプル用のGET APIエンドポイント
 * OpenAPI spec version: 1.0.0
 */
import { customInstance } from '../lib/custom-instance';
export type GetUsersParams = {
/**
 * フィルタリング用の名前（文字列）
 */
name?: string;
/**
 * 取得件数の上限（数値）
 * @minimum 1
 * @maximum 100
 * @nullable
 */
limit?: number | null;
/**
 * フィルタリング用のタグ配列
 */
tags?: string[];
};

export type GetUsers200Item = {
  id?: number;
  name?: string;
  email?: string;
  created_at?: string;
};

export type GetUsers500 = {
  error?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  /**
 * システムに登録されているユーザーの一覧を取得します
 * @summary ユーザー一覧を取得
 */
export const getUsers = (
    params?: GetUsersParams,
 options?: SecondParameter<typeof customInstance>,) => {
      return customInstance<GetUsers200Item[]>(
      {url: `http://localhost:4010/api/users`, method: 'GET',
        params
    },
      options);
    }
  
export type GetUsersResult = NonNullable<Awaited<ReturnType<typeof getUsers>>>
